Teams:
  red:
	name: "Rouge"
	colors: "§4"
	data: 14
   blue:
   	name: "Bleu"
	colors: "§9"
	data: 11
   yellow:
	name: "Jaune"
	colors: "§e"
	data: 4
   green:
    name: "verte"
    colors: "§a"
	data: 5
